/** i18n 키 → 한글 라벨 매핑 (symbolism 출력용) */
export const SYMBOL_LABELS: Record<string, string> = {
  "symbol.planet.saturn": "토성",
  "symbol.planet.venus": "금성",
  "symbol.planet.sun": "태양",
  "symbol.planet.pluto": "명왕성",
  "symbol.planet.mercury": "수성",
  "symbol.planet.uranus": "천왕성",
  "symbol.planet.jupiter": "목성",
  "symbol.planet.mars": "화성",
  "symbol.planet.moon": "달",
  "symbol.stone.diamond": "다이아몬드",
  "symbol.stone.emerald": "에메랄드",
  "symbol.stone.sapphire": "사파이어",
  "symbol.stone.amethyst": "자수정",
  "symbol.stone.topaz": "토파즈",
  "symbol.stone.ruby": "루비",
  "symbol.stone.opal": "오팔",
  "symbol.stone.garnet": "가넷",
  "symbol.stone.moonstone": "월장석",
  "symbol.flower.whiterose": "화이트 로즈",
  "symbol.flower.primrose": "앵초",
  "symbol.flower.sunflower": "해바라기",
  "symbol.flower.orchid": "난초",
  "symbol.flower.lily_valley": "은방울꽃",
  "symbol.flower.rose": "장미",
  "symbol.flower.dahlia": "다홍색",
  "symbol.flower.peony": "모란",
  "symbol.flower.poppy": "양귀비",
  "symbol.tarot.justice": "정의",
  "symbol.tarot.empress": "여황제",
  "symbol.tarot.star": "별",
  "symbol.tarot.emperor": "황제",
  "symbol.tarot.hierophant": "교황",
  "symbol.tarot.lovers": "연인",
  "symbol.tarot.chariot": "전차",
  "symbol.tarot.strength": "힘",
  "symbol.tarot.hermit": "은둔자",
  "item.compass": "나침반",
  "item.scale": "저울",
  "item.heart": "하트",
  "item.gift": "선물",
  "item.crown": "왕관",
  "item.trophy": "트로피",
  "item.mirror": "거울",
  "item.palette": "팔레트",
  "item.book": "책",
  "item.lens": "렌즈",
  "item.shield": "방패",
  "item.anchor": "닻",
  "item.dice": "주사위",
  "item.sword": "검",
  "item.lotus": "연꽃",
};

export function getSymbolLabel(key: string): string {
  return SYMBOL_LABELS[key] ?? key.split(".").pop() ?? key;
}
