openapi: 3.0.0
info:
  title: Next Enneagram API
  version: 1.0.0
paths:
  /api/enneagram/questions:
    get:
      summary: Get questions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
  /api/enneagram/enneagrams:
    get:
      summary: Get enneagram type information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Enneagram'
  /api/enneagram/submit:
    post:
      summary: Submit answers and get result type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answers:
                  type: array
                  items:
                    $ref: '#/components/schemas/Answer'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
        '500':
          description: Server error
components:
  schemas:
    Question:
      type: object
      properties:
        seq:
          type: integer
        type:
          type: integer
        question:
          type: string
    Answer:
      type: object
      properties:
        seq:
          type: integer
        type:
          type: integer
        answer:
          type: integer
    Enneagram:
      type: object
      properties:
        type:
          type: integer
        title:
          $ref: '#/components/schemas/EnneagramTitle'
        core_fear:
          type: string
        core_desire:
          type: string
        summary:
          type: string
        description:
          type: string
        wings:
          type: array
          items:
            $ref: '#/components/schemas/EnneagramWing'
    EnneagramTitle:
      type: object
      properties:
        korean:
          type: string
        english:
          type: string
    EnneagramWing:
      type: object
      properties:
        type:
          type: integer
        title:
          $ref: '#/components/schemas/EnneagramTitle'
        description:
          type: string
